// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-QeMG1Q7qNYNRcYVbTYtwmcFHyGkIQ0',
    appId: '1:667209165373:web:0a27a005d720b23886d854',
    messagingSenderId: '667209165373',
    projectId: 'mpl-lab-67b9c',
    authDomain: 'mpl-lab-67b9c.firebaseapp.com',
    storageBucket: 'mpl-lab-67b9c.firebasestorage.app',
    measurementId: 'G-C4K021E0HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZrRJ1DmwqUkn-xn71DKms85gVwjF9yDc',
    appId: '1:667209165373:android:24936b030b185d9086d854',
    messagingSenderId: '667209165373',
    projectId: 'mpl-lab-67b9c',
    storageBucket: 'mpl-lab-67b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkEHgtNbcye1zGCQa7os6FSc442fT5YQ',
    appId: '1:667209165373:ios:fc00bdd373357f0b86d854',
    messagingSenderId: '667209165373',
    projectId: 'mpl-lab-67b9c',
    storageBucket: 'mpl-lab-67b9c.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSkEHgtNbcye1zGCQa7os6FSc442fT5YQ',
    appId: '1:667209165373:ios:fc00bdd373357f0b86d854',
    messagingSenderId: '667209165373',
    projectId: 'mpl-lab-67b9c',
    storageBucket: 'mpl-lab-67b9c.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD-QeMG1Q7qNYNRcYVbTYtwmcFHyGkIQ0',
    appId: '1:667209165373:web:8d1e84b8e18bb34586d854',
    messagingSenderId: '667209165373',
    projectId: 'mpl-lab-67b9c',
    authDomain: 'mpl-lab-67b9c.firebaseapp.com',
    storageBucket: 'mpl-lab-67b9c.firebasestorage.app',
    measurementId: 'G-3J5B0QLQDX',
  );
}
